spin_version = "1"
authors = ["Philippe Charrière <ph.charriere@gmail.com>"]
description = "hello world demo"
name = "go-hello-world"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "go-hello-world"
source = "main.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -wasm-abi=generic -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
