spin_version = "1"
authors = ["Philippe Charrière <ph.charriere@gmail.com>"]
description = "hello world"
name = "rust-hello-world"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "rust-hello-world"
source = "target/wasm32-wasi/release/rust_hello_world.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
